### ISSUE TITLE
Some usability problem

### ISSUE THREAD

**Issue by erik0704** [CS2103AUG2017-W15-B1/Main#79] opened 2017-11-03 07:32 UTC
- Commands do not load error message & examples when the enter command is in the wrong format. In the basic Address Book level 4 there were proper indications.

- Similarly commands should announce whether the execution is successful (e.g. when running `export` command the user has to go manually check the desktop to see the export is success, as the app shows no indication.)

**Comment by john19950730** [comment] 2017-11-03 07:53
Hi, thanks for testing our application. In reply to your comments:

Firstly, can you please specify which commands do not load error messages, so as to help us reproduce the lack of error messages?

Secondly, in response to your report that `export` command giving no indication of successful execution.
![image](https://user-images.githubusercontent.com/17763037/32364276-e1670a9a-c0ae-11e7-8988-16e98dc20ba4.png)
Does this not seem like an _indication_ of the export being **successful**?

**Comment by erik0704** [comment] 2017-11-03 08:26
The `DisplayResult` UI component did not load when I first started the jar file. However it worked when I restarted the application. I am unable to reproduce it as of now. Will look into it again soon.

**Comment by john19950730** [comment] 2017-11-07 13:57
This issue is most likely caused by the bug highlighted in the other issue. Closing.

**Closed as completed by john19950730** 2017-11-07 13:57 UTC
