### ISSUE TITLE
Select command

### ISSUE THREAD

**Issue by erik0704** [CS2103AUG2017-W15-B1/Main#76] opened 2017-11-03 07:30 UTC
Unsure as to what exactly the `select` command does. User guide does not say besides simply selecting. The person card does not lit up nor any success indication shows.

**Comment by freesoup** [comment] 2017-11-03 07:45
Hi could you include a screenshot, we were not able to reproduce the problem.

**Comment by john19950730** [comment] 2017-11-07 13:49
Believed to be caused by a bug highlighted in another issue. Closing.

**Closed as completed by john19950730** 2017-11-07 13:49 UTC
