### ISSUE TITLE
UI components hang bug reproduce

### ISSUE THREAD

**Issue by erik0704** [CS2103AUG2017-W15-B1/Main#81] opened 2017-11-03 08:45 UTC
Ok I managed to reproduce the bug using v1.4 jar file via these steps:

- Start the app

- Run `help` command via the command box. The user guide helpwindow will pop out

- Switch back to the main app. Run any command. Every UI component will hang except the `PersonListPanel`. The `ResultDisplay` box will not display anything. `Select` comman fail to load google search & google map. All functionality will work during this time, but the hanged UI components will only resume after the `HelpWindow` is closed.

The bug is pretty major since we need to see the user guide while operating the app.

It is especially interesting because it only happens when the HelpWindow is access via the command. If it is accessed via pressing F1 or manually navigate via the top bar then the bug does not happen.

**Comment by erik0704** [comment] 2017-11-03 09:17
@damithc I just realize that our group also like this so apparently this is a global bug originate from the main addressbook-level4 module repo.

**Comment by john19950730** [comment] 2017-11-03 09:33
I believe the problem is produced by `help` command pausing the execution of commands while the help window is displayed.
I think this problem is seriously worth looking into, and if this bug happens for every fork of AB L4, this bug ought to be escalated to the relevant authors of `help` command.

**Comment by damithc** [comment] 2017-11-03 11:33
> @damithc I just realize that our group also like this so apparently this is a global bug originate from the main addressbook-level4 module repo.

Yup. https://github.com/nus-cs2103-AY1718S1/forum/issues/181

**Comment by john19950730** [comment] 2017-11-17 02:15
Fixed thanks to quick fix brought up on the forum. Closing.

**Closed as completed by john19950730** 2017-11-17 02:15 UTC
